spring:
  application:
    name: fms-backend-api
  datasource:
    username: fmsapi
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://100.100.112.9:5432/fms_dev
    password: skibididopdopyesyes
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  web:
    resources:
      add-mappings: true