name: Deploy Test Environment

on:
  push:
    branches:
      - test

jobs:
  build-and-deploy:
    runs-on: self-hosted
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        run: echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk" >> $GITHUB_ENV
        shell: bash

      - name: Verify Java version
        run: java -version

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: sechmachine/fms:test

      - name: Recreate container with Portainer webhook
        run: |
          curl -X POST --insecure https://100.100.112.9:9443/api/webhooks/2e5f4b34-174e-4fdf-8a5b-f6e0763c1f27
          echo "Container recreated"