name: Rebase Test onto Main on Pull Request close

on:
  pull_request:
    types: [ closed ]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  rebase:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Fetch all branches
        run: git fetch --all

      - name: Rebase test onto main
        run: |
          git checkout test
          git rebase main

      - name: Push changes
        run: git push origin test --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}